# Generated by Django 5.2.1 on 2025-05-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AGE', models.IntegerField()),
                ('GENDER', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')])),
                ('DIABETES', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('DIABETES_TYPE', models.IntegerField(choices=[(1, 'Tipo 1'), (2, 'Tipo 2')])),
                ('DIARRHOEA', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('SHORT_STATURE', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('STICKY_STOOL', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('WEIGHT_LOSS', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')])),
                ('IGA', models.FloatField()),
                ('IGG', models.FloatField()),
                ('IGM', models.FloatField()),
                ('DISEASE_DIAGOSE', models.IntegerField(choices=[(0, 'Negativo'), (1, 'Positivo')])),
                ('PROBABILITY', models.FloatField(help_text='Probabilidad de predicción en %')),
            ],
        ),
    ]
