# Generated by Django 5.2.1 on 2025-05-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiWebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(choices=[(18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (56, '56'), (57, '57'), (58, '58'), (59, '59'), (60, '60'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (66, '66'), (67, '67'), (68, '68'), (69, '69'), (70, '70'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75'), (76, '76'), (77, '77'), (78, '78'), (79, '79'), (80, '80'), (81, '81'), (82, '82'), (83, '83'), (84, '84'), (85, '85'), (86, '86'), (87, '87'), (88, '88'), (89, '89'), (90, '90'), (91, '91'), (92, '92'), (93, '93'), (94, '94'), (95, '95'), (96, '96'), (97, '97'), (98, '98'), (99, '99'), (100, '100')], default=30)),
                ('gender', models.IntegerField(choices=[(0, 'Masculino'), (1, 'Femenino')], default=0)),
                ('diabetes', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], default=0)),
                ('diabetes_type', models.IntegerField(choices=[(1, 'Tipo 1'), (2, 'Tipo 2')], default=2)),
                ('diarrhoea', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], default=0)),
                ('short_stature', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], default=0)),
                ('sticky_stool', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], default=0)),
                ('weight_loss', models.IntegerField(choices=[(0, 'No'), (1, 'Sí')], default=0)),
                ('iga', models.FloatField(default=0.0)),
                ('igg', models.FloatField(default=0.0)),
                ('igm', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientData',
        ),
    ]
